
# Task name - used to pick the class to load
task_name: ${task.name}

# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 8

minibatch_size: 16

# seed - set to -1 to choose random seed
seed: 40
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: 5000

## Device config
physics_engine: 'physx'

# whether to use cpu or gpu pipeline
pipeline: 'cpu'

# whether to use cpu or gpu physx
sim_device: 'cpu'

# used for gpu simulation only - device id for running sim and task if pipeline=gpu
device_id: 0

# device to run RL
rl_device: 'cuda:0'
#rl_device: 'cpu'

# multi-GPU training
multi_gpu: False

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False

debug: False

# used to set checkpoint path
checkpoint: ''

# disables rendering
headless: False
# enables native livestream
enable_livestream: False
# timeout for MT script
mt_timeout: 300

# enables viewport recording
enable_recording: False
# interval between video recordings (in steps)
recording_interval: 2000
# length of the recorded video (in steps)
recording_length: 300
# fps for writing recorded video
recording_fps: 30
# directory to save recordings in
recording_dir: ''

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'omniisaacgymenvs'

# path to a kit app common
kit_app: ''

# Warp
warp: False

# set default task and default training config based on task
defaults:
  - task: Crossing
  - train: SAC
  - hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .

